version: '3'
services:
    web:
        depends_on: 
            - zookeeper
            - redis
        environment: 
            - ZOOKEEPER_URI=zookeeper:1234
        build: .
        ports:
            - "8000:8000"
        networks: 
            - web-go
    zookeeper:
        image: zookeeper
        container_name: zoo
        restart: always
        hostname: zoo1
        volumes:
            - /home/hoang/zookeeper:/data
        ports:
            - 1234:1234
        networks: 
            - web-go   
    redis:
        image: redis:alpine
        container_name: red
        ports: ["6379"]
        networks:
            - web-go
networks: 
    web-go: